### PR TITLE
Only Part 2 does not have the part from part 1 need to add it

### PR DESCRIPTION
**Pull request by chaim-f**
/*variables I am assuming are somehow passed to me */
vector<Player> pList;
Map* aMap;
/*Functions I need added in the Map class
NumberOfTerritories(); return territoriesVec.size(); or equivlent
aTterritoriesVec(int value); return territoriesVec.at(value) gives me access to any territory in the territoriesVec by a index. 

variable and functions I need added in Player (it should be useful for the reinforcement stage too)
int reinforcePool; //stores the number of how many troops the player has left to allocate. can be left alone as it will be intialzed before the first turn
int getreinforcePool(); return reinforcePool;
void setreinforcePool(int value); reinforcePool = value;
*/

### CODE REVIEW

**Comment by tramyardg** [comment]
@chaim-f once my part is merged  you can get 
- your `vector pList;` from `g.getPlayersCreated()` (it is a function that returns players vector)
- you can get your `NumberOfTerritories();` from `getChosenMap().size()` it is a vector that returns the territories chosen by user in the start up phase.
- Similarly, `territoriesVec.at(value) ` = `getChosenMap().at(i)` to get a specific territory.

- Note: `g.getPlayersCreated()` will suppose to give you the list of players but still not working because of player class need to be fixed.

**Review by tramyardg — APPROVED** [review]

**Comment by chaim-f** [comment]
@tramyardg for validating if all territories are assigned, I was thinking of adding a bool wasAllocated  which will be set to false by default and a function for changing it in the Map class (access through the vector Territory list and a index), and a function for verifying in the map class) as this is your class do you have a better way of doing it?

**Comment by tramyardg** [comment]
Sure you can do it like this.

**Comment by tramyardg** [comment]
You can make a copy of the Territory list and manipulate any way you want.

**Pull request merged**
